url: http://jsonapi.org
source: .
destination: ./public

# github pages we cannot customize
lsi: false
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jemoji
incremental: false
gist:
  noscript: false
# customize github pages
quiet: false
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: false
  template: '' # cannot customize
  math_engine: mathjax # cannot customize
  syntax_highligher: rouge # cannot customize

gems:
  - jekyll-redirect-from

exclude:
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - ./public
  - ./stylesheets/*.scss

port: 9876

collections:
  format:
    output: true

defaults:
  - scope:
      path: ""
      type: format
    values:
      layout: page
      show_sidebar: true
      is_spec_page: true

latest_version: 1.0
excerpt_separator: ""

navigation:
- title: JSON API
  url: /json-api/
- title: Specification
  url: /json-api/format/
- title: Extensions
  url: /json-api/extensions/
- title: Recommendations
  url: /json-api/recommendations/
- title: Examples
  url: /json-api/examples/
- title: Implementations
  url: /json-api/implementations/
- title: FAQ
  url: /json-api/faq/
- title: About
  url: /json-api/about/

quicklinks:
- title: View the specification
  url: /json-api/format/
